"""
Darwin Bot Arena — Physics Engine
==================================
DO NOT EDIT THIS FILE.

Real pymunk rigid-body physics. Validated stable.
"""

import math, os, json, tempfile
import pymunk
import neat

GRAVITY       = (0, 980)
DAMPING       = 0.97
SUBSTEPS      = 10
DT            = 1 / 60
SIM_SECONDS   = 10.0
GROUND_Y      = 400
PIXELS_PER_M  = 100

THIGH_L    = 55
SHIN_L     = 48
THIGH_W    = 10
SHIN_W     = 9
TORSO_H    = 18
TORSO_MASS = 5.0
LEG_MASS   = 0.7
HIP_FORCE  = 900_000
KNEE_FORCE = 700_000
HIP_LIM    = 1.0
KNEE_LIM   = 1.2
MAX_RATE   = 6.0


def _build_creature(space, n_legs, start_x, start_y, thigh_l, shin_l, hip_lim, knee_lim):
    TORSO_W = max(60, n_legs * 28)
    tm = pymunk.moment_for_box(TORSO_MASS, (TORSO_W, TORSO_H))
    tb = pymunk.Body(TORSO_MASS, tm)
    tb.position = (start_x, start_y)
    ts = pymunk.Poly.create_box(tb, (TORSO_W, TORSO_H))
    ts.friction = 0.5; ts.elasticity = 0.0
    ts.filter = pymunk.ShapeFilter(group=1)
    space.add(tb, ts)

    motors = []
    for i in range(n_legs):
        hx = start_x - TORSO_W/2 + (TORSO_W/n_legs)*(i+0.5)
        hy = start_y + TORSO_H/2
        thigh_cy = hy + thigh_l/2

        thm = pymunk.moment_for_box(LEG_MASS, (THIGH_W, thigh_l))
        thb = pymunk.Body(LEG_MASS, thm)
        thb.position = (hx, thigh_cy)
        ths = pymunk.Poly.create_box(thb, (THIGH_W, thigh_l))
        ths.friction = 0.5; ths.elasticity = 0.0
        ths.filter = pymunk.ShapeFilter(group=1)
        space.add(thb, ths)

        shin_cy = thigh_cy + thigh_l/2 + shin_l/2
        shm = pymunk.moment_for_box(LEG_MASS*0.5, (SHIN_W, shin_l))
        shb = pymunk.Body(LEG_MASS*0.5, shm)
        shb.position = (hx, shin_cy)
        shs = pymunk.Poly.create_box(shb, (SHIN_W, shin_l))
        shs.friction = 1.5; shs.elasticity = 0.0
        shs.filter = pymunk.ShapeFilter(group=1)
        space.add(shb, shs)

        hpj = pymunk.PivotJoint(tb, thb, (hx, hy))
        hpj.error_bias = pow(1-0.1, 60)
        hpm = pymunk.SimpleMotor(tb, thb, 0)
        hpm.max_force = HIP_FORCE
        hpl = pymunk.RotaryLimitJoint(tb, thb, -hip_lim, hip_lim)
        space.add(hpj, hpm, hpl)

        kpj = pymunk.PivotJoint(thb, shb, (hx, thigh_cy+thigh_l/2))
        kpj.error_bias = pow(1-0.1, 60)
        kpm = pymunk.SimpleMotor(thb, shb, 0)
        kpm.max_force = KNEE_FORCE
        kpl = pymunk.RotaryLimitJoint(thb, shb, 0.0, knee_lim)
        space.add(kpj, kpm, kpl)

        motors.append({'hip': hpm, 'knee': kpm, 'thigh': thb, 'shin': shb,
                       'shin_l': shin_l})
    return tb, motors


def _get_sensors(torso, motors, hip_lim, knee_lim):
    sensors = [
        math.sin(torso.angle),
        math.cos(torso.angle),
        torso.velocity.y / 500.0,
    ]
    for m in motors:
        thigh_rel = m['thigh'].angle - torso.angle
        knee_rel  = m['shin'].angle  - m['thigh'].angle
        sensors.append(thigh_rel / hip_lim)
        sensors.append(knee_rel  / knee_lim)
        shin_tip_y = m['shin'].position.y + m['shin_l']/2
        sensors.append(1.0 if shin_tip_y > GROUND_Y - 12 else 0.0)
    return sensors


def _apply_outputs(outputs, motors):
    for i, m in enumerate(motors):
        hi, ki = i*2, i*2+1
        if hi < len(outputs):
            m['hip'].rate  = float(outputs[hi]) * MAX_RATE
        if ki < len(outputs):
            m['knee'].rate = float(outputs[ki]) * MAX_RATE


def _is_fallen(torso, spawn_y):
    if torso.position.y > spawn_y + 30:   # torso dropped >30px from start
        return True
    if abs(torso.angle) > 0.7:            # ~40 degrees tilt
        return True
    return False


def _spawn_y(thigh_l, shin_l):
    return GROUND_Y - thigh_l - shin_l - TORSO_H - 20


def evaluate_genome(genome, config, body_spec, fitness_fn, metrics_fn=None):
    n_legs    = body_spec["n_legs"]
    thigh_l   = int(body_spec.get("thigh_len",  THIGH_L / PIXELS_PER_M) * PIXELS_PER_M)
    shin_l    = int(body_spec.get("shin_len",   SHIN_L  / PIXELS_PER_M) * PIXELS_PER_M)
    hip_lim   = body_spec.get("hip_range",  HIP_LIM)
    knee_lim  = body_spec.get("knee_range", KNEE_LIM)

    space = pymunk.Space()
    space.gravity = GRAVITY
    space.damping = DAMPING
    ground = pymunk.Segment(space.static_body, (-99999, GROUND_Y), (99999, GROUND_Y), 4)
    ground.friction = 1.2; ground.elasticity = 0.0
    space.add(ground)

    torso, motors = _build_creature(space, n_legs, 300, _spawn_y(thigh_l, shin_l),
                                    thigh_l, shin_l, hip_lim, knee_lim)
    net = neat.nn.FeedForwardNetwork.create(genome, config)

    for _ in range(int(0.4/DT)):
        for __ in range(SUBSTEPS):
            space.step(DT/SUBSTEPS)

    start_x  = torso.position.x
    spawn_y  = torso.position.y          # record settled resting height
    falls = 0; fell_last = False
    prev_vx = 0.0; total_jerk = 0.0; step_count = 0
    legs_active_frames = 0               # frames where ≥half the legs touched ground
    custom_totals = {}                   # accumulated custom metrics from metrics_fn
    steps = int(SIM_SECONDS / DT)

    for _ in range(steps):
        sensors = _get_sensors(torso, motors, hip_lim, knee_lim)
        outputs = net.activate(sensors)
        _apply_outputs(outputs, motors)
        for __ in range(SUBSTEPS):
            space.step(DT/SUBSTEPS)
        vx = torso.velocity.x
        if vx > 5:
            step_count += 1
        total_jerk += abs(vx - prev_vx)
        prev_vx = vx
        # count legs with foot near ground
        feet_down = sum(
            1 for m in motors
            if m['shin'].position.y + m['shin_l']/2 > GROUND_Y - 12
        )
        if feet_down >= max(1, n_legs // 2):
            legs_active_frames += 1
        if _is_fallen(torso, spawn_y):
            if not fell_last: falls += 1
            fell_last = True
        else:
            fell_last = False

        # call student metrics hook if provided
        if metrics_fn is not None:
            step_data = {
                "vx":           vx,
                "vy":           torso.velocity.y,
                "torso_angle":  torso.angle,
                "torso_height": GROUND_Y - torso.position.y,
                "feet_down":    feet_down,
                "fallen":       fell_last,
            }
            custom = metrics_fn(step_data)
            if custom:
                for k, v in custom.items():
                    custom_totals[k] = custom_totals.get(k, 0) + v

    distance   = max(0.0, (torso.position.x - start_x) / PIXELS_PER_M)
    smoothness = 1.0 / (1.0 + total_jerk / max(steps, 1))
    legs_active = round(legs_active_frames / max(steps, 1), 4)   # 0.0–1.0 fraction of run
    raw = {"distance": round(distance,4), "falls": falls,
           "smoothness": round(smoothness,4), "step_count": step_count,
           "legs_active": legs_active}
    raw.update(custom_totals)   # merge in any student-defined metrics
    fitness = fitness_fn(raw)
    genome.fitness = fitness
    raw["fitness"] = round(fitness, 4)
    return raw


def run_evolution(team_folder, body_spec, fitness_fn,
                  config_path=None, generations=50,
                  verbose=True, visual=True, gen_counter=None,
                  metrics_fn=None):

    if config_path is None:
        config_path = os.path.join(team_folder, "config.ini")

    n_legs   = body_spec["n_legs"]
    thigh_l  = int(body_spec.get("thigh_len",  THIGH_L / PIXELS_PER_M) * PIXELS_PER_M)
    shin_l   = int(body_spec.get("shin_len",   SHIN_L  / PIXELS_PER_M) * PIXELS_PER_M)
    _patch_config(config_path, 3 + n_legs*3, n_legs*2)

    with open(config_path, "r", encoding="utf-8") as f:
        raw = f.read()
    ascii_raw = raw.encode("ascii", errors="ignore").decode("ascii")
    tmp = tempfile.NamedTemporaryFile(mode="w", suffix=".ini", delete=False, encoding="ascii")
    tmp.write(ascii_raw); tmp.close()
    config = neat.Config(neat.DefaultGenome, neat.DefaultReproduction,
                         neat.DefaultSpeciesSet, neat.DefaultStagnation, tmp.name)
    os.unlink(tmp.name)

    population  = neat.Population(config)
    best_scores = []
    best_ever   = {"fitness": 0, "distance": 0, "falls": 0, "smoothness": 0, "step_count": 0}
    best_genome  = [None]
    best_cfg_ref = [None]
    quit_visual  = [False]

    def eval_genomes(genomes, cfg):
        best_this = -9999; best_g = None; best_s = None
        for gid, genome in genomes:
            score = evaluate_genome(genome, cfg, body_spec, fitness_fn, metrics_fn)
            if score["fitness"] > best_this:
                best_this = score["fitness"]; best_g = genome; best_s = score
        best_scores.append(best_this)
        if best_s and best_this > best_ever["fitness"]:
            best_ever.update(best_s); best_genome[0] = best_g; best_cfg_ref[0] = cfg

        gen = len(best_scores)
        if gen_counter is not None:
            gen_counter[0] = gen
        if verbose:
            print(f"  >> Gen {gen:>3} | fit: {best_this:>8.3f} | "
                  f"dist: {best_s['distance']:>5.2f}m | falls: {best_s['falls']} | "
                  f"best: {best_ever['distance']:.2f}m")
        if visual and not quit_visual[0] and best_genome[0] is not None:
            _replay(best_genome[0], best_cfg_ref[0], body_spec, gen, best_ever, quit_visual)
        _write_score(team_folder, {"generation": gen,
            "best_fitness": round(best_ever["fitness"],4),
            "distance": best_ever["distance"],
            "step_count": best_ever["step_count"],
            "history": best_scores[-50:]})

    winner = population.run(eval_genomes, generations)
    final  = evaluate_genome(winner, config, body_spec, fitness_fn, metrics_fn)
    _write_score(team_folder, {"generation": generations,
        "best_fitness": final["fitness"], "distance": final["distance"],
        "step_count": final["step_count"], "history": best_scores})
    if verbose:
        print(f"\n  Done! Best distance: {final['distance']:.2f}m")
    return winner, config


LEG_COLORS = [(80,130,210),(120,190,100),(210,130,80),(180,80,170),(80,190,190),(210,210,80)]

def _replay(genome, config, body_spec, gen_num, best_ever, quit_flag):
    try:
        import pygame
    except ImportError:
        return
    n_legs   = body_spec["n_legs"]
    thigh_l  = int(body_spec.get("thigh_len",  THIGH_L / PIXELS_PER_M) * PIXELS_PER_M)
    shin_l   = int(body_spec.get("shin_len",   SHIN_L  / PIXELS_PER_M) * PIXELS_PER_M)
    hip_lim  = body_spec.get("hip_range",  HIP_LIM)
    knee_lim = body_spec.get("knee_range", KNEE_LIM)
    TORSO_W = max(60, n_legs*28)
    W, H = 960, 480
    pygame.init()
    screen = pygame.display.set_mode((W, H))
    pygame.display.set_caption(f"Darwin Bot - Gen {gen_num}")
    clock = pygame.time.Clock()
    font_l = pygame.font.SysFont("monospace", 15)
    font_s = pygame.font.SysFont("monospace", 12)

    space = pymunk.Space(); space.gravity = GRAVITY; space.damping = DAMPING
    ground = pymunk.Segment(space.static_body, (-99999,GROUND_Y),(99999,GROUND_Y),4)
    ground.friction=1.2; ground.elasticity=0.0; space.add(ground)
    torso, motors = _build_creature(space, n_legs, 300, _spawn_y(thigh_l, shin_l),
                                    thigh_l, shin_l, hip_lim, knee_lim)
    net = neat.nn.FeedForwardNetwork.create(genome, config)

    for _ in range(int(0.4/DT)):
        for __ in range(SUBSTEPS): space.step(DT/SUBSTEPS)

    start_x = torso.position.x
    spawn_y = torso.position.y
    steps   = int(SIM_SECONDS/DT)

    for step in range(steps):
        for event in pygame.event.get():
            if event.type == pygame.QUIT or (
                event.type == pygame.KEYDOWN and event.key == pygame.K_ESCAPE):
                quit_flag[0] = True; pygame.quit(); return

        sensors = _get_sensors(torso, motors, hip_lim, knee_lim)
        outputs = net.activate(sensors)
        _apply_outputs(outputs, motors)
        for _ in range(SUBSTEPS): space.step(DT/SUBSTEPS)

        camera_x = torso.position.x - W//3
        screen.fill((242, 240, 234))

        # Ground + markers
        pygame.draw.line(screen,(140,125,105),(0,GROUND_Y),(W,GROUND_Y),3)
        for m in range(-1, 40):
            mx = int(m*PIXELS_PER_M - camera_x)
            if 0 <= mx <= W:
                pygame.draw.line(screen,(195,185,170),(mx,GROUND_Y-8),(mx,GROUND_Y+3),1)
                screen.blit(font_s.render(f"{m}m",True,(175,162,145)),(mx-10,GROUND_Y+5))

        # Legs
        for i, m in enumerate(motors):
            col = LEG_COLORS[i % len(LEG_COLORS)]
            dark = tuple(max(0,c-50) for c in col)
            thb = m['thigh']; shb = m['shin']
            hx_w = torso.position.x - TORSO_W/2 + (TORSO_W/n_legs)*(i+0.5)
            hy_w = torso.position.y + TORSO_H/2
            kx = thb.position.x + thigh_l/2*math.sin(thb.angle)
            ky = thb.position.y + thigh_l/2*math.cos(thb.angle)
            fx = shb.position.x + shin_l/2*math.sin(shb.angle)
            fy = shb.position.y + shin_l/2*math.cos(shb.angle)
            def s(wx,wy): return (int(wx-camera_x), int(wy))
            pygame.draw.line(screen,col,s(hx_w,hy_w),s(kx,ky),6)
            pygame.draw.line(screen,dark,s(kx,ky),s(fx,fy),5)
            pygame.draw.circle(screen,(220,215,200),s(fx,fy),5)

        # Torso (rotated rect)
        tx = int(torso.position.x - camera_x); ty = int(torso.position.y)
        ang = torso.angle; hw,hh = TORSO_W/2, TORSO_H/2
        corners = [(tx+(dx*math.cos(ang)-dy*math.sin(ang)),
                    ty+(dx*math.sin(ang)+dy*math.cos(ang)))
                   for dx,dy in [(-hw,-hh),(hw,-hh),(hw,hh),(-hw,hh)]]
        pygame.draw.polygon(screen,(65,65,78),corners)
        pygame.draw.polygon(screen,(90,90,105),corners,2)

        # HUD
        dist = max(0.0,(torso.position.x-start_x)/PIXELS_PER_M)
        status = "FALLEN" if _is_fallen(torso, spawn_y) else "walking"
        for j,line in enumerate([
            f"Gen {gen_num}  |  {dist:.2f}m  [{status}]",
            f"Best ever: {best_ever['distance']:.2f}m",
            "ESC = skip previews"]):
            screen.blit(font_l.render(line,True,(50,50,50)),(12,12+j*22))

        pygame.display.flip()
        clock.tick(120)

    pygame.quit()


def _replay_standalone(genome, config, body_spec):
    quit_flag = [False]
    best_ever = {"distance": 0}
    while not quit_flag[0]:
        _replay(genome, config, body_spec, "watch", best_ever, quit_flag)


def _write_score(team_folder, data):
    path = os.path.join(team_folder, "score.json")
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2)


def _patch_config(config_path, num_inputs, num_outputs):
    with open(config_path, "r", encoding="utf-8") as f:
        lines = f.readlines()
    with open(config_path, "w", encoding="utf-8") as f:
        for line in lines:
            if line.strip().startswith("num_inputs"):
                f.write(f"num_inputs  = {num_inputs}\n")
            elif line.strip().startswith("num_outputs"):
                f.write(f"num_outputs = {num_outputs}\n")
            else:
                f.write(line)